name=Lib1090
Version=1.0.0
author=Sybren Postma <sybren.postma@achron.eu>
maintainer=Sybren Postma <sybren.postma@achron.eu>
sentence=LR2021 driver library for ADS-B reception at 1090 MHz
category=communication
url=https://github.com/GeneralSyb/Lib1090
architectures=*
